In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [13]:
df=pd.read_csv('train.csv',index_col='Id')

In [14]:
df

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                      
1             60       RL         65.0     8450   Pave   NaN      Reg   
2             20       RL         80.0     9600   Pave   NaN      Reg   
3             60       RL         68.0    11250   Pave   NaN      IR1   
4             70       RL         60.0     9550   Pave   NaN      IR1   
5             60       RL         84.0    14260   Pave   NaN      IR1   
...          ...      ...          ...      ...    ...   ...      ...   
1456          60       RL         62.0     7917   Pave   NaN      Reg   
1457          20       RL         85.0    13175   Pave   NaN      Reg   
1458          70       RL         66.0     9042   Pave   NaN      Reg   
1459          20       RL         68.0     9717   Pave   NaN      Reg   
1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities LotConfig  ... PoolArea PoolQC  Fence MiscFeature  \
Id                                    ...                                      
1            Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
2            Lvl    AllPub       FR2  ...        0    NaN    NaN         NaN   
3            Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
4            Lvl    AllPub    Corner  ...        0    NaN    NaN         NaN   
5            Lvl    AllPub       FR2  ...        0    NaN    NaN         NaN   
...          ...       ...       ...  ...      ...    ...    ...         ...   
1456         Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
1457         Lvl    AllPub    Inside  ...        0    NaN  MnPrv         NaN   
1458         Lvl    AllPub    Inside  ...        0    NaN  GdPrv        Shed   
1459         Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
1460         Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   

     MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                               
1          0      2    2008        WD         Normal     208500  
2          0      5    2007        WD         Normal     181500  
3          0      9    2008        WD         Normal     223500  
4          0      2    2006        WD        Abnorml     140000  
5          0     12    2008        WD         Normal     250000  
...      ...    ...     ...       ...            ...        ...  
1456       0      8    2007        WD         Normal     175000  
1457       0      2    2010        WD         Normal     210000  
1458    2500      5    2010        WD         Normal     266500  
1459       0      4    2010        WD         Normal     142125  
1460       0      6    2008        WD         Normal     147500  

[1460 rows x 80 columns]

# Indexing using square brackets

In [15]:
df['LotFrontage'][1457]

85.0

# Using column a!ribute and row label

In [16]:
df.MSSubClass[4]

70

# Using the .loc accessor

In [17]:
df.loc[4, 'MSSubClass'] 


70

# Using the .iloc accessor

In [18]:
 df.iloc[4, 2] 

84.0

In [19]:
 type(df['MSSubClass'])

pandas.core.series.Series

# Slicing and indexing a Series


In [20]:
df['MSSubClass'][1:4]

Id
2    20
3    60
4    70
Name: MSSubClass, dtype: int64

In [21]:
df['MSSubClass'][4]

70

# All columns comes in between

In [24]:
#All rows, some columns  
df.loc[:, 'MSSubClass':'LotArea'] 

MSSubClass MSZoning  LotFrontage  LotArea
Id                                             
1             60       RL         65.0     8450
2             20       RL         80.0     9600
3             60       RL         68.0    11250
4             70       RL         60.0     9550
5             60       RL         84.0    14260
...          ...      ...          ...      ...
1456          60       RL         62.0     7917
1457          20       RL         85.0    13175
1458          70       RL         66.0     9042
1459          20       RL         68.0     9717
1460          20       RL         75.0     9937

[1460 rows x 4 columns]

In [26]:
# Some rows, all columns 
df.loc[1:5,:]

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
4           70       RL         60.0     9550   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
4          Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

   MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                             
1        0      2    2008        WD         Normal     208500  
2        0      5    2007        WD         Normal     181500  
3        0      9    2008        WD         Normal     223500  
4        0      2    2006        WD        Abnorml     140000  
5        0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

In [28]:
df.loc[1:5, 'MSSubClass':'LotArea'] 

MSSubClass MSZoning  LotFrontage  LotArea
Id                                           
1           60       RL         65.0     8450
2           20       RL         80.0     9600
3           60       RL         68.0    11250
4           70       RL         60.0     9550
5           60       RL         84.0    14260

# Using .iloc[]

In [29]:
 df.iloc[2:5, 1:] 

MSZoning  LotFrontage  LotArea Street Alley LotShape LandContour Utilities  \
Id                                                                              
3        RL         68.0    11250   Pave   NaN      IR1         Lvl    AllPub   
4        RL         60.0     9550   Pave   NaN      IR1         Lvl    AllPub   
5        RL         84.0    14260   Pave   NaN      IR1         Lvl    AllPub   

   LotConfig LandSlope  ... PoolArea PoolQC Fence MiscFeature MiscVal  MoSold  \
Id                      ...                                                     
3     Inside       Gtl  ...        0    NaN   NaN         NaN       0       9   
4     Corner       Gtl  ...        0    NaN   NaN         NaN       0       2   
5        FR2       Gtl  ...        0    NaN   NaN         NaN       0      12   

    YrSold  SaleType  SaleCondition SalePrice  
Id                                             
3     2008        WD         Normal    223500  
4     2006        WD        Abnorml    140000  
5     2008        WD         Normal    250000  

[3 rows x 79 columns]

In [62]:
df.loc[3:6, ['MSZoning', 'LotArea']]

MSZoning  LotArea
Id                  
3        RL    11250
4        RL     9550
5        RL    14260
6        RL    14115

In [63]:
df1=df.iloc[[0,4,5,6,7], 0:5] 


In [64]:
df1

MSSubClass MSZoning  LotFrontage  LotArea Street
Id                                                  
1           60       RL         65.0     8450   Pave
5           65       RL         84.0    14260   Pave
6           55       RL         85.0    14115   Pave
7           25       RL         75.0    10084   Pave
8           65       RL          NaN    10382   Pave

# Filtering

In [65]:
df1.LotFrontage>65

Id
1    False
5     True
6     True
7     True
8    False
Name: LotFrontage, dtype: bool

In [66]:
df1[df1.LotFrontage>65]

MSSubClass MSZoning  LotFrontage  LotArea Street
Id                                                  
5           65       RL         84.0    14260   Pave
6           55       RL         85.0    14115   Pave
7           25       RL         75.0    10084   Pave

In [67]:
df1[(df1.MSSubClass >= 50) & (df1.LotArea < 10382)] #both condition should satisfied

MSSubClass MSZoning  LotFrontage  LotArea Street
Id                                                  
1           60       RL         65.0     8450   Pave

In [68]:
df1[(df1.MSSubClass >= 50) | (df1.LotArea < 10382)] #Atlist one condition satisfied

MSSubClass MSZoning  LotFrontage  LotArea Street
Id                                                  
1           60       RL         65.0     8450   Pave
5           65       RL         84.0    14260   Pave
6           55       RL         85.0    14115   Pave
7           25       RL         75.0    10084   Pave
8           65       RL          NaN    10382   Pave

In [69]:
 df1.loc[:, df1.any()] 

MSSubClass MSZoning  LotFrontage  LotArea Street
Id                                                  
1           60       RL         65.0     8450   Pave
5           65       RL         84.0    14260   Pave
6           55       RL         85.0    14115   Pave
7           25       RL         75.0    10084   Pave
8           65       RL          NaN    10382   Pave

In [70]:
df1.loc[:, df1.notnull().all()] #Without null values columns

MSSubClass MSZoning  LotArea Street
Id                                     
1           60       RL     8450   Pave
5           65       RL    14260   Pave
6           55       RL    14115   Pave
7           25       RL    10084   Pave
8           65       RL    10382   Pave

In [71]:
df1.dropna(how='any') #Drop row with NAN values

MSSubClass MSZoning  LotFrontage  LotArea Street
Id                                                  
1           60       RL         65.0     8450   Pave
5           65       RL         84.0    14260   Pave
6           55       RL         85.0    14115   Pave
7           25       RL         75.0    10084   Pave

In [72]:
df1.MSSubClass[df1.LotArea > 8450] #Filtering a column based on another

Id
5    65
6    55
7    25
8    65
Name: MSSubClass, dtype: int64

In [73]:
df1.MSSubClass[df1.LotArea > 8450] += 5 #Modifying a column based on another

C:\Users\nikhi\AppData\Local\Temp/ipykernel_2008/3189611477.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.MSSubClass[df1.LotArea > 8450] += 5


In [74]:
df1

MSSubClass MSZoning  LotFrontage  LotArea Street
Id                                                  
1           60       RL         65.0     8450   Pave
5           70       RL         84.0    14260   Pave
6           60       RL         85.0    14115   Pave
7           30       RL         75.0    10084   Pave
8           70       RL          NaN    10382   Pave

In [76]:
df2=df.iloc[[0,4,5,6,7], 0:5]

In [77]:
df2

MSSubClass MSZoning  LotFrontage  LotArea Street
Id                                                  
1           60       RL         65.0     8450   Pave
5           65       RL         84.0    14260   Pave
6           55       RL         85.0    14115   Pave
7           25       RL         75.0    10084   Pave
8           65       RL          NaN    10382   Pave

In [80]:
#np.floor_divide(df1, 5)
df2['MSSubClass'].floordiv(5) # divid

Id
1    12
5    13
6    11
7     5
8    13
Name: MSSubClass, dtype: int64

In [83]:
df2.Street = df2.Street.str.upper() #for upper case /lower case

In [84]:
df2.Street

Id
1    PAVE
5    PAVE
6    PAVE
7    PAVE
8    PAVE
Name: Street, dtype: object

In [86]:
df2['ms_lo'] = df.MSSubClass + df.LotFrontage # add two numerical columns

In [87]:
df2

MSSubClass MSZoning  LotFrontage  LotArea Street  ms_lo
Id                                                         
1           60       RL         65.0     8450   PAVE  125.0
5           65       RL         84.0    14260   PAVE  149.0
6           55       RL         85.0    14115   PAVE  140.0
7           25       RL         75.0    10084   PAVE  100.0
8           65       RL          NaN    10382   PAVE    NaN

# NUMPY

In [107]:
a = np.arange(10).reshape(2,-1)


In [108]:
b = np.repeat(1, 10).reshape(2,-1)

In [109]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [110]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [111]:
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [112]:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [113]:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])